### ISSUE TITLE
Error: Space Between Parens

### ISSUE THREAD

**Issue by popcorn245** [sasstools/gulp-sass-lint#1]
When linting with the beta release the code returns this error. If I have Alpha-4 this doesn't occur.  If I had some spare time I would do a bit more debugging, but just reporting for now. Thanks! ^_^

```
C:\xampp\htdocs\MadnessPlatform\node_modules\gulp-sass-lint\node_modules\sass-lint\lib\rules\space-between-parens.js:40
        if (first.type === 'space') {
                 ^
TypeError: Cannot read property 'type' of undefined
    at C:\xampp\htdocs\MadnessPlatform\node_modules\gulp-sass-lint\node_modules\sass-lint\lib\rules\space-between-parens.js:40:18
    at RootNode.traverseByType (C:\xampp\htdocs\MadnessPlatform\node_modules\gulp-sass-lint\node_modules\sass-lint\node_modules\gonzales-pe\lib\node\root-node.js:1:1739)
    at Object.module.exports.detect (C:\xampp\htdocs\MadnessPlatform\node_modules\gulp-sass-lint\node_modules\sass-lint\lib\rules\space-between-parens.js:15:9)
    at C:\xampp\htdocs\MadnessPlatform\node_modules\gulp-sass-lint\node_modules\sass-lint\index.js:50:25
    at Array.forEach (native)
    at Function.sassLint.lintText (C:\xampp\htdocs\MadnessPlatform\node_modules\gulp-sass-lint\node_modules\sass-lint\index.js:49:9)
    at DestroyableTransform._transform (C:\xampp\htdocs\MadnessPlatform\node_modules\gulp-sass-lint\index.js:32:27)
    at DestroyableTransform.Transform._read (C:\xampp\htdocs\MadnessPlatform\node_modules\gulp-sass-lint\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (C:\xampp\htdocs\MadnessPlatform\node_modules\gulp-sass-lint\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:160:12)
    at doWrite (C:\xampp\htdocs\MadnessPlatform\node_modules\gulp-sass-lint\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:326:12)
```

**Comment by minamarkham** [comment]
I'm having the same issue.

**Comment by Snugug** [comment]
Gulp Sass Lint is a thin wrapper around [Sass Lint](https://github.com/sasstools/sass-lint/issues). Please re-file your issue there, and include the failing Sass.
