### ISSUE TITLE
Syntax errors break watch

### ISSUE THREAD

**Issue by popcorn245** [sasstools/gulp-sass-lint#18]
Every time you miss closing parens or any other syntax errors it kills my watch.  Is there a way around this as it is very annoying to have to restart my build every time I mistype and it's the only linter that does it, even the ruby linter for sass doesn't. Any help is greatly appreciated, thanks! ^_^

PS - I have tried using plumber and a standard on('error'... to no avail and I would rather not clone the repo and manually edit with as frequently as this one updates. Also, it freaks out about line endings which is really annoying when git natively wants to "fix" them.

Thanks for making this plugin as I want to stay as far away from (shivers) ruby as I can.

**Comment by xzyfer** [comment]
This is how Gulp works. This has been fixed in Gulp 4. If you're using Gulp 3 you can use [gulp-plumber](https://github.com/floatdrop/gulp-plumber) to fix this.

```
gulp.src('./src/*.ext')
    .pipe(plumber())
    .pipe(sassLint())
    .pipe(sassLint.format())
    .pipe(sassLint.failOnError())
```

**Comment by Snugug** [comment]
Please include the error you're getting. 

You can omit the failOnError pipe which will stop it from failing on errors

**Comment by ubenzer** [comment]
I have the same problem. The line throws exception is not `failOnError`, it is `sassLint()`.

Exception:

```
Error: Parsing error at app/scss/_colors.scss: Please check validity of the block starting from line #94
    at module.exports (/Users/ub/Playground/savedo-banking-app/node_modules/sass-lint/lib/groot.js:21:11)
    at Function.sassLint.lintText (/Users/ub/Playground/savedo-banking-app/node_modules/sass-lint/index.js:36:13)
    at DestroyableTransform._transform (/Users/ub/Playground/savedo-banking-app/node_modules/gulp-sass-lint/index.js:38:27)
    at DestroyableTransform.Transform._read (/Users/ub/Playground/savedo-banking-app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/ub/Playground/savedo-banking-app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/ub/Playground/savedo-banking-app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
    at writeOrBuffer (/Users/ub/Playground/savedo-banking-app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:319:5)
    at DestroyableTransform.Writable.write (/Users/ub/Playground/savedo-banking-app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at write (/Users/ub/Playground/savedo-banking-app/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/ub/Playground/savedo-banking-app/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/ub/Playground/savedo-banking-app/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:68:13)
    at DestroyableTransform.emit (events.js:167:7)
    at emitReadable_ (/Users/ub/Playground/savedo-banking-app/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/ub/Playground/savedo-banking-app/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/ub/Playground/savedo-banking-app/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
```

It is coming from `sass-lint` and not handled.

**Comment by Bnaya** [comment]
I have also this issue and i can't overcome it with the suggested methods

**Comment by colin-marshall** [comment]
Same issue here. Looks like it is happening when there is a variable interpolated in a property. See the `margin` property:

``` scss
@mixin accordion-container {
  list-style-type: none;
  background: $accordion-background;
  border: $accordion-content-border;
  border-radius: $global-radius;
  margin-#{$global-left}: 0;
}
```

Here is the error message:

```
/Users/colinmarshall/Projects/Forks/foundation-sites/node_modules/sass-lint/lib/groot.js:21
    throw new Error('Parsing error' + fileInfo + ': ' + e.message);
    ^

Error: Parsing error at scss/components/_accordion.scss: Please check validity of the block starting from line #51
    at module.exports (/Users/colinmarshall/Projects/Forks/foundation-sites/node_modules/sass-lint/lib/groot.js:21:11)
    at Function.sassLint.lintText (/Users/colinmarshall/Projects/Forks/foundation-sites/node_modules/sass-lint/index.js:36:13)
    at DestroyableTransform._transform (/Users/colinmarshall/Projects/Forks/foundation-sites/node_modules/gulp-sass-lint/index.js:38:27)
    at DestroyableTransform.Transform._read (/Users/colinmarshall/Projects/Forks/foundation-sites/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/colinmarshall/Projects/Forks/foundation-sites/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/colinmarshall/Projects/Forks/foundation-sites/node_modules/readable-stream/lib/_stream_writable.js:333:12)
    at writeOrBuffer (/Users/colinmarshall/Projects/Forks/foundation-sites/node_modules/readable-stream/lib/_stream_writable.js:319:5)
    at DestroyableTransform.Writable.write (/Users/colinmarshall/Projects/Forks/foundation-sites/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at write (/Users/colinmarshall/Projects/Forks/foundation-sites/node_modules/gulp-plumber/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/colinmarshall/Projects/Forks/foundation-sites/node_modules/gulp-plumber/node_modules/readable-stream/lib/_stream_readable.js:632:7)
```

I've added `gulp-plumber` and removed the `failOnError` pipe as suggested but that does not solve the issue.

**Comment by DanPurdy** [comment]
@colin-marshall That is a parse error with the AST we're using `gonzales-pe`, it doesn't handle interpolation well in the current version. It fails because the AST itself has given up so we can't lint on a broken tree. You'll want to file these issues over [here](https://github.com/tonyganch/gonzales-pe) as there isn't much we can do about it right now I'm afraid. 

The PR in #20 could be a solution to stop watch breaking but it wont handle the underlying failure from the AST meaning you'd need re-lint...

**Comment by ubenzer** [comment]
Hi @DanPurdy, in my opinion if sass is not parsable then nothing to lint, user should fix parser errors and create a valid sass first. Not linting a file is not a problem in that point. But, files with parse error should fail gracefully.

**Comment by DanPurdy** [comment]
Definitely, I think it's an issue in sass-lint itself though really, throwing errors isn't really too useful as it is done currently.

I'm going to look at including parse errors as just plain lint errors in `sass-lint` soon so that they can be handled in a similar fashion. As for that PR i've pinged the owner of this repo on a similar matter brought up with regards to file ignores so I'll see what happens there and get back to this.

**Comment by ubenzer** [comment]
Many thanks. :)

**Comment by DanPurdy** [comment]
I've put in a PR over at sass-lint to return these errors as lint errors rather than un handled error throws, hopefully that should get through once I've updated the tests. This will prevent these errors from breaking watch tasks and also allow other files without parse errors to still be linted correctly.

**Comment by Chris-May** [comment]
I'm a bit confused about the state of this issue. Up to now it seems as though:
1. This tool is ready for when sass-lint gets updated. (as of 1.1.1?)
2. Dan [put in a PR](https://github.com/sasstools/sass-lint/pull/459), which looks like it was merged to `sasstools:develop` on Jan 20. (Thanks for doing that!)
3. Which means it might have been released to the with sass-lint version 1.5.0 (or 1.5.1 at the latest?)

But my watch task is still dying from error, specifically:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Cannot read property 'start' of undefined
```

On the surface, it seems it might not be related to this tool, but that error is only present when I have the sassLint pipe lines in there.

I'm running sass-lint 1.5.1 and gulp-sass-lint 1.1.1

**Comment by DanPurdy** [comment]
So this is actually an error in one of the rules that's being thrown and is definitely a sass-lint crash. My first guess would be one of the following.
- You're using windows with CRLF line endings
- You're using hard tabs
- You have one of the above and you're using the indentation rule

If not i can take more guesses :smile:

**Comment by Chris-May** [comment]
Drat. looks like I'm got a guessing game on hand. 
I'm on a mac, using spaces.
I'm thinking I should be focusing on the yml, which we generated with make-sass-lint-config v0.1.1, right?

**Comment by DanPurdy** [comment]
Ha no, it's just unfortunately it's become my standard response to check those things while we were waiting for our AST to update. Is there any more to the error, a rule name or something?

**Comment by Chris-May** [comment]
Sadly, no. Just surrounded by a sea of unhelpful non-context. :disappointed: 

```
sass/global/_functions.scss
   4:29  warning  Space expected after `:`  space-after-colon
   4:39  warning  Space expected after `:`  space-after-colon
  14:18  warning  Space expected after `:`  space-after-colon
  14:35  warning  Space expected after `:`  space-after-colon
  14:48  warning  Space expected after `:`  space-after-colon

✖ 5 problems (0 errors, 5 warnings)


events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Cannot read property 'start' of undefined
```
